class McDonaldsMenu {
  static Map<String, List<dynamic>> products = {
    'Big Mac': [
      5.69,
      'assets/images/big_mac.jpg',
      'Big Mac',
      'Beef patty, lettuce, cheese, pickles, onions, sesame seed bun',
      4.5,
      120,
      'The iconic Big Mac is made with two beef patties, special sauce, lettuce, cheese, pickles, and onions on a sesame seed bun.', // Description
    ],
    'French Fries': [
      2.99,
      'assets/images/french_fries.jpg',
      'French Fries',
      'Potatoes, salt, oil',
      4.7,
      200,
      'Crispy on the outside and fluffy on the inside, our fries are the perfect side to any meal.',
    ],
    'McChicken': [
      4.19,
      'assets/images/mcchicken.jpg',
      'McChicken',
      'Chicken patty, lettuce, mayonnaise, bun',
      4.3,
      150,
      'A juicy chicken patty topped with crisp lettuce and creamy mayonnaise, all in a toasted bun.',
    ],
    'Filet-O-Fish': [
      4.49,
      'assets/images/filet_o_fish.jpg',
      'Filet-O-Fish',
      'Fish fillet, tartar sauce, cheese, bun',
      4.1,
      100,
      'A tender fish fillet, topped with tartar sauce and a slice of cheese, served on a steamed bun.',
    ],
    'McFlurry': [
      3.49,
      'assets/images/mcflurry.jpg',
      'McFlurry',
      'Ice cream, mixed toppings',
      4.6,
      80,
      'Our delicious McFlurry is a creamy soft-serve ice cream blended with your choice of toppings.',
    ],
    'Apple Pie': [
      1.29,
      'assets/images/apple_pie.jpg',
      'Apple Pie',
      'Apples, cinnamon, pastry crust',
      4.4,
      130,
      'Enjoy a warm, flaky pastry filled with sweet apples and cinnamon, perfect for dessert.',
    ],
    'Happy Meal': [
      4.99,
      'assets/images/happy_meal.jpg',
      'Happy Meal',
      'Choice of burger or nuggets, fries, drink, toy',
      4.8,
      220,
      'A meal that comes with your choice of a burger or chicken nuggets, fries, a drink, and a fun toy.',
    ],
    'Soft Drink': [
      1.89,
      'assets/images/soft_drink.jpg',
      'Soft Drink',
      'Carbonated beverage',
      4.5,
      300,
      'Choose from a variety of soft drinks to quench your thirst with every meal.',
    ],
    'Chicken McNuggets': [
      4.39,
      'assets/images/chicken_mcnuggets.jpg',
      'Chicken McNuggets',
      'Chicken, batter, sauce',
      4.4,
      160,
      'Tender and juicy chicken nuggets served with your choice of dipping sauce.',
    ],
    'Sundae': [
      2.49,
      'assets/images/sundae.jpg',
      'Sundae',
      'Ice cream, chocolate or caramel topping, nuts, cherry',
      4.3,
      90,
      'A classic ice cream sundae topped with your choice of chocolate or caramel and a cherry on top.',
    ],
    'Double Quarter Pounder': [
      6.19,
      'assets/images/double_quarter_pounder.jpg',
      'Double Quarter Pounder',
      'Two beef patties, cheese, pickles, onions, ketchup, mustard, sesame seed bun',
      4.5,
      110,
      'A burger featuring two quarter-pound beef patties, melted cheese, and all the fixings.',
    ],
    'McCafe Coffee': [
      2.29,
      'assets/images/mccafe_coffee.jpg',
      'McCafe Coffee',
      'Brewed coffee',
      4.6,
      250,
      'Rich and flavorful coffee brewed fresh daily to kickstart your day.',
    ],
    'Quarter Pounder': [
      4.89,
      'assets/images/quarter_pounder.png',
      'Quarter Pounder',
      'Beef patty, cheese, pickles, onions, ketchup, mustard, sesame seed bun',
      4.4,
      130,
      'A classic burger featuring a quarter-pound beef patty with all your favorite toppings.',
    ],
    'Chocolate Shake': [
      3.59,
      'assets/images/chocolate_shake.png',
      'Chocolate Shake',
      'Milk, chocolate syrup, whipped cream',
      4.2,
      70,
      'Creamy chocolate shake topped with whipped cream for a delicious treat.',
    ],
    'Egg McMuffin': [
      3.89,
      'assets/images/egg_mcmuffin.png',
      'Egg McMuffin',
      'Egg, Canadian bacon, cheese, English muffin',
      4.7,
      200,
      'A delicious breakfast sandwich featuring a freshly cracked egg, Canadian bacon, and melted cheese.',
    ],
    'Fruit & Maple Oatmeal': [
      2.99,
      'assets/images/fruit_maple_oatmeal.png',
      'Fruit & Maple Oatmeal',
      'Oatmeal, fruit, brown sugar',
      4.5,
      50,
      'Warm oatmeal topped with fresh fruit and a touch of brown sugar for a wholesome breakfast.',
    ],
    'Salad': [
      4.29,
      'assets/images/salad.png',
      'Salad',
      'Mixed greens, cherry tomatoes, dressing',
      4.0,
      80,
      'Fresh salad with mixed greens and cherry tomatoes, served with your choice of dressing.',
    ],
    'Cheeseburger': [
      1.99,
      'assets/images/cheeseburger.png',
      'Cheeseburger',
      'Beef patty, cheese, pickles, onions, ketchup, mustard, bun',
      4.3,
      190,
      'A classic cheeseburger made with a juicy beef patty and melted cheese.',
    ],
    'Hot Fudge Sundae': [
      2.99,
      'assets/images/hot_fudge_sundae.png',
      'Hot Fudge Sundae',
      'Ice cream, hot fudge, whipped cream, nuts',
      4.6,
      120,
      'A decadent sundae with rich hot fudge sauce over creamy vanilla ice cream.',
    ],
    'McDouble': [
      3.39,
      'assets/images/mcdouble.png',
      'McDouble',
      'Two beef patties, cheese, pickles, onions, ketchup, mustard, bun',
      4.2,
      140,
      'A value option featuring two beef patties and melted cheese for double the flavor.',
    ],
  };
}
